export const enum Route {
  MAIN_STACK = 'MAIN_STACK',
  TAB_STACK = 'TAB_STACK',
  //Tab
  TAB1_SCREEN = 'TAB1_SCREEN',
  TAB2_SCREEN = 'TAB2_SCREEN',
  TAB3_SCREEN = 'TAB3_SCREEN',

  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SIGN_UP_SCREEN = 'SIGN_UP_SCREEN',
}
