export const enum Route {
  MAIN_STACK = 'MAIN_STACK',
  TAB_STACK = 'TAB_STACK',
  //Tab
  TASK_SCREEN = 'TASK_SCREEN',
  HOME_SCREEN = 'HOME_SCREEN',
  NOTE_SCREEN = 'NOTE_SCREEN',

  //Common
  TASK_CREATE_AND_EDIT_SCREEN = 'TASK_CREATE_AND_EDIT_SCREEN',
  NOTE_CREATE_AND_EDIT_SCREEN = 'NOTE_CREATE_AND_EDIT_SCREEN',

  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SIGN_UP_SCREEN = 'SIGN_UP_SCREEN',
}
